kind: pipeline
name: Pipeline

steps:
- name: build
  image: golang
  commands:
  - go get -v -t -d ./...
  - go build
      
- name: testing
  image: golang
  commands:
  - go get -v -t -d ./...
  - go test -v ./...

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: usuario
    password:
      from_secret: pass
    repo: desckjet/drone:2
    compress: true
    tags:
      - 1.0.2
      - latest
  when:
    branch:
    - master